import { readFile } from "node:fs/promises";
import path from "node:path";
import { NextResponse } from "next/server";
import { requireAiOpsActor } from "@/lib/ai-ops-auth";
import { aiOpsDownloads, aiOpsEndpoints, aiOpsSkillName } from "@/lib/ai-ops-links";
import { getSiteSettings } from "@/lib/settings";
import { createZipArchive } from "@/lib/zip";

export const runtime = "nodejs";

const packageName = `${aiOpsSkillName}.zip`;

function projectFile(...segments: string[]) {
  return path.join(process.cwd(), ...segments);
}

function packageReadme(baseUrl: string) {
  return `# OpenWebsite AI Ops Skill Package

This archive lets Codex-style agents connect to the OpenWebsite AI operations API.

## Contents

- \`SKILL.md\`: Codex skill entrypoint.
- \`references/api.md\`: Endpoint payload and response reference.
- \`agents/openai.yaml\`: Agent display metadata.
- \`docs/AI_OPERATIONS.md\`: Human-facing operations guide.
- \`manifest.json\`: Runtime connection hints generated by this site.

## Install

Unzip this archive into a Codex skills directory so the final path is:

\`\`\`text
~/.codex/skills/openwebsite-ai-ops/SKILL.md
\`\`\`

Then configure the target site and token:

\`\`\`bash
export OPENWEBSITE_BASE_URL="${baseUrl}"
export AI_OPS_TOKEN="replace-with-the-site-token"
curl -H "Authorization: Bearer $AI_OPS_TOKEN" "$OPENWEBSITE_BASE_URL/api/ai/context"
\`\`\`

Use API writes for content, media, and SEO updates. Avoid direct database edits unless the API cannot
express the operation.
`;
}

export async function GET(request: Request) {
  const { actor, response } = await requireAiOpsActor(request);
  if (!actor) return response;

  const settings = await getSiteSettings();
  const baseUrl = settings.siteUrl || new URL(request.url).origin;
  const generatedAt = new Date();
  const [skill, apiReference, agentConfig, operationsGuide] = await Promise.all([
    readFile(projectFile("skills", aiOpsSkillName, "SKILL.md"), "utf8"),
    readFile(projectFile("skills", aiOpsSkillName, "references", "api.md"), "utf8"),
    readFile(projectFile("skills", aiOpsSkillName, "agents", "openai.yaml"), "utf8"),
    readFile(projectFile("docs", "AI_OPERATIONS.md"), "utf8")
  ]);

  const manifest = {
    name: aiOpsSkillName,
    product: "OpenWebsite",
    generatedAt: generatedAt.toISOString(),
    baseUrl,
    site: {
      name: settings.siteName,
      defaultLocale: settings.defaultLocale,
      supportedLocales: settings.supportedLocales
    },
    auth: {
      type: "bearer",
      env: "AI_OPS_TOKEN",
      header: "Authorization: Bearer ${AI_OPS_TOKEN}"
    },
    endpoints: aiOpsEndpoints,
    downloads: aiOpsDownloads,
    install: {
      codexSkillPath: "~/.codex/skills/openwebsite-ai-ops",
      entrypoint: "SKILL.md"
    }
  };

  const archive = createZipArchive([
    {
      path: `${aiOpsSkillName}/SKILL.md`,
      content: skill,
      modifiedAt: generatedAt
    },
    {
      path: `${aiOpsSkillName}/references/api.md`,
      content: apiReference,
      modifiedAt: generatedAt
    },
    {
      path: `${aiOpsSkillName}/agents/openai.yaml`,
      content: agentConfig,
      modifiedAt: generatedAt
    },
    {
      path: `${aiOpsSkillName}/docs/AI_OPERATIONS.md`,
      content: operationsGuide,
      modifiedAt: generatedAt
    },
    {
      path: `${aiOpsSkillName}/README.md`,
      content: packageReadme(baseUrl),
      modifiedAt: generatedAt
    },
    {
      path: `${aiOpsSkillName}/manifest.json`,
      content: `${JSON.stringify(manifest, null, 2)}\n`,
      modifiedAt: generatedAt
    }
  ]);

  return new NextResponse(new Uint8Array(archive), {
    headers: {
      "cache-control": "no-store",
      "content-disposition": `attachment; filename="${packageName}"`,
      "content-length": String(archive.length),
      "content-type": "application/zip"
    }
  });
}
